### ISSUE TITLE
Kibana installation failing because of systemd dependency

### ISSUE THREAD

**Issue by sn-dp** [anuriq/chef-kibana5#39]
Error executing action `configure` on resource 'kibana5_configure[kibana]'
    

    NoMethodError
    -------------
    undefined method `description' for Custom resource systemd_service from cookbook systemd

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/kibana5/resources/configure.rb:34:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/kibana5/resources/configure.rb:33:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/kibana5/recipes/default.rb

     21: kibana5_configure 'kibana' do
     22:   configuration 'server.port' => node['kibana5']['config']['server.port'],
     23:                 'server.host' => node['kibana5']['config']['server.host'],
     24:                 'elasticsearch.url' => node['kibana5']['config']['elasticsearch.url'],
     25:                 'logging.dest' => node['kibana5']['config']['logging.dest']
     26: end

**Comment by anuriq** [comment]
Hi @sn-dp 
Are you sure, you are using latest version of this cookbook and `systemd` cookbook?

**Comment by TheKatarGit** [comment]
@sn-dp this issue will be fixed in #37

**Comment by sn-dp** [comment]
Hi **@anuriq** 
 _systemd_ version in locked to a specific version. I 'm able to replicate issue with _systemd_ cookbook version being (3.2.3)

Hi **@TheKatarGit** 
#37 did fixed issue. However, a small change to xpack config is done to install kibana 6.2.3.

**Comment by TheKatarGit** [comment]
@sn-dp could you please clarify what change is required?
